## Deliverable 2. Create a Customer Travel Destinations Map.

In [5]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [6]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,port hardy,CA,2021-12-12 23:21:39,50.6996,-127.4199,37.40,93,75,6.91,light rain,0.0,0
1,1,victoria point,AU,2021-12-12 23:21:39,-27.5833,153.3000,81.48,61,25,5.01,scattered clouds,0.0,0
2,2,yellowknife,CA,2021-12-12 23:21:39,62.4560,-114.3525,8.56,89,90,8.05,light snow,0.0,0
3,3,rio gallegos,AR,2021-12-12 23:21:36,-51.6226,-69.2181,53.65,20,40,27.63,scattered clouds,0.0,0
4,4,leningradskiy,RU,2021-12-12 23:21:40,69.3833,178.4167,-31.25,91,3,4.41,clear sky,0.0,0

In [7]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_prompt_temp = float(input('What is the minimum temperature you would like for your trip? '))
max_prompt_temp = float(input('What is the maximum temperature you would like for your trip? '))

What is the minimum temperature you would like for your trip? 70
What is the maximum temperature you would like for your trip? 80

In [10]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_temp_df = city_data_df.loc[( city_data_df['Max Temp']<=max_prompt_temp)&
                                    ( city_data_df['Max Temp']>=min_prompt_temp)]
preferred_temp_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
12,12,sao jose da coroa grande,BR,2021-12-12 23:21:42,-8.8978,-35.1478,79.14,79,22,11.12,few clouds,0.0,0
13,13,ondjiva,AO,2021-12-12 23:21:42,-17.0667,15.7333,71.15,71,93,1.68,light rain,0.0,0
20,20,rikitea,PF,2021-12-12 23:21:44,-23.1203,-134.9692,77.65,76,87,8.63,light rain,0.0,0
25,25,port alfred,ZA,2021-12-12 23:21:46,-33.5906,26.8910,71.02,96,100,14.23,overcast clouds,0.0,0
26,26,cassilandia,BR,2021-12-12 23:21:46,-19.1133,-51.7342,75.63,82,97,4.74,light rain,0.0,0

In [11]:
# 4a. Determine if there are any empty rows.
clean_preferred_temp_df = preferred_temp_df.dropna()
clean_preferred_temp_df.count()

City_ID                     171
City                        171
Country                     171
Date                        171
Lat                         171
Lng                         171
Max Temp                    171
Humidity                    171
Cloudiness                  171
Wind Speed                  171
Current Description         171
Rain inches (last 3 hrs)    171
Snow inches (last 3 hrs)    171
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.

In [12]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_preferred_temp_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
12,sao jose da coroa grande,BR,79.14,few clouds,-8.8978,-35.1478,
13,ondjiva,AO,71.15,light rain,-17.0667,15.7333,
20,rikitea,PF,77.65,light rain,-23.1203,-134.9692,
25,port alfred,ZA,71.02,overcast clouds,-33.5906,26.8910,
26,cassilandia,BR,75.63,light rain,-19.1133,-51.7342,
35,pimentel,PE,71.89,clear sky,-6.8367,-79.9342,
37,saint-philippe,RE,76.59,broken clouds,-21.3585,55.7679,
43,bambous virieux,MU,73.65,broken clouds,-20.3428,57.7575,
45,castro,BR,71.85,overcast clouds,-24.7911,-50.0119,
49,atar,MR,70.83,broken clouds,20.5169,-13.0499,

In [14]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

    # 6c. Get latitude and longitude from DataFrame

    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    

    # 6e. Make request and retrieve the JSON data from the search. 
   
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    
for index, row in hotel_df.iterrows():
    lat = row['Lat']
    lng = row['Lng']

    base_url = 'https://maps.googleapis.com/maps/api/place/nearbysearch/json?'
    params = {'key': g_key, 'type':'lodging', 'radius' : 5000}
    params['location'] = f"{lat},{lng}"
    try: 
        req_hotels = requests.get(base_url, params= params).json()

        hotel_df.loc[index, 'Hotel Name'] = req_hotels['results'][0]['name']
    except (IndexError):
        print('Hotel not found... skipping')

Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping
Hotel not found... skipping

In [15]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()
clean_hotel_df.count()

City                   171
Country                171
Max Temp               171
Current Description    171
Lat                    171
Lng                    171
Hotel Name             171
dtype: int64

In [17]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/Weather_vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [18]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
gmaps.configure(api_key = g_key)
locations = clean_hotel_df[['Lat','Lng']]
info_box_template = '''
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}°F</dd>
</dl>'''

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [23]:
# 11a. Add a marker layer for each city to the map. 

# 11b. Display the figure
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows() ]
fig = gmaps.figure(center = (30.0,31.0), zoom_level = 1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content = hotel_info)
fig.add_layer(marker_layer)
fig

Figure(layout=FigureLayout(height='420px'))